# Generated by Django 3.2.7 on 2021-11-30 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('postId', models.AutoField(primary_key=True, serialize=False)),
                ('postTitle', models.CharField(max_length=200)),
                ('postDescription', models.CharField(max_length=1000)),
                ('postLikes', models.IntegerField(default=0)),
                ('postLocation', models.CharField(max_length=200)),
                ('foodType', models.CharField(max_length=200)),
                ('postDate', models.DateTimeField()),
                ('postOwnerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('videoId', models.AutoField(primary_key=True, serialize=False)),
                ('videoName', models.CharField(max_length=100)),
                ('videoType', models.CharField(max_length=100)),
                ('postVideoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.post')),
            ],
        ),
        migrations.CreateModel(
            name='SavedPost',
            fields=[
                ('SavedPostId', models.AutoField(primary_key=True, serialize=False)),
                ('inheritedPostId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.post')),
                ('userSavedPostId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('photoId', models.AutoField(primary_key=True, serialize=False)),
                ('photoName', models.CharField(max_length=100)),
                ('photoType', models.CharField(max_length=100)),
                ('postPhotoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.post')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('commentId', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=1000)),
                ('commentOwnerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('postCommentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.post')),
            ],
        ),
    ]
