# Generated by Django 3.2.7 on 2021-11-30 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_comment_photo_post_savedpost_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='questionTag',
            field=models.CharField(default='Title', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='questionTitle',
            field=models.CharField(default='Tag', max_length=200),
            preserve_default=False,
        ),
    ]
