# Generated by Django 3.2.7 on 2021-12-02 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211130_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userbio',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photoType',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
