# Generated by Django 3.2.7 on 2021-12-03 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_post_postdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='UserPhotoName',
            field=models.CharField(blank=True, default='default.jpg', max_length=200),
        ),
    ]
