# Generated by Django 3.2.7 on 2021-12-03 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_user_userphotoname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='UserPhotoName',
            field=models.CharField(blank=True, default='default.png', max_length=200),
        ),
    ]
